name: Format suggestions
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Format suggestion with JuliaFormatter.jl

        uses: julia-actions/julia-format@v4
        with:
          version: '2'
          suggestion-label: 'format-suggest'
